### ISSUE TITLE
Missing repositories?

### ISSUE THREAD

**Issue by novacain1** [jnunyez/k8s-deviceFarmer#2]
Error: initializing source docker://quay.io/jnunez/adb:latest: reading manifest latest in quay.io/jnunez/adb: unauthorized: access to the requested resource is not authorized

Suspect that these repos are not public, and I am not in the allowed user listing?

**Comment by jnunyez** [comment]
adb repo set to public.

**Comment by novacain1** [comment]
thanks, looks like a few more @jnunyez:

Error: initializing source docker://quay.io/jnunez/rethinkdb:2.3: reading manifest 2.3 in quay.io/jnunez/rethinkdb: unauthorized: access to the requested resource is not authorized
125

Error: initializing source docker://quay.io/jnunez/stf:v3.6.1: reading manifest v3.6.1 in quay.io/jnunez/stf: unauthorized: access to the requested resource is not authorized
125

**Comment by jnunyez** [comment]
Fixed.
